# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted VS2017

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PipAuthenticate@1
  inputs:
    artifactFeeds: 'package01'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install PythonPackage'